// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt5-term-api-health-check.proto

package mt5_term_api;

public final class Mt5TermApiHealthCheck {
  private Mt5TermApiHealthCheck() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StopListeningRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt5_term_api.StopListeningRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code mt5_term_api.StopListeningRequest}
   */
  public static final class StopListeningRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt5_term_api.StopListeningRequest)
      StopListeningRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StopListeningRequest.newBuilder() to construct.
    private StopListeningRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopListeningRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StopListeningRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StopListeningRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest.class, mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest)) {
        return super.equals(obj);
      }
      mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest other = (mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt5_term_api.StopListeningRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt5_term_api.StopListeningRequest)
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest.class, mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest.Builder.class);
      }

      // Construct using mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningRequest_descriptor;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest getDefaultInstanceForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest.getDefaultInstance();
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest build() {
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest buildPartial() {
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest result = new mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest) {
          return mergeFrom((mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest other) {
        if (other == mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt5_term_api.StopListeningRequest)
    }

    // @@protoc_insertion_point(class_scope:mt5_term_api.StopListeningRequest)
    private static final mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest();
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopListeningRequest>
        PARSER = new com.google.protobuf.AbstractParser<StopListeningRequest>() {
      @java.lang.Override
      public StopListeningRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopListeningRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopListeningRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopListeningRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt5_term_api.Mt5TermApiHealthCheck.StopListeningRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StopListeningReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt5_term_api.StopListeningReply)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code mt5_term_api.StopListeningReply}
   */
  public static final class StopListeningReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt5_term_api.StopListeningReply)
      StopListeningReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StopListeningReply.newBuilder() to construct.
    private StopListeningReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StopListeningReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StopListeningReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private StopListeningReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply.class, mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply)) {
        return super.equals(obj);
      }
      mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply other = (mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt5_term_api.StopListeningReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt5_term_api.StopListeningReply)
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply.class, mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply.Builder.class);
      }

      // Construct using mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_StopListeningReply_descriptor;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply getDefaultInstanceForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply.getDefaultInstance();
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply build() {
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply buildPartial() {
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply result = new mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply) {
          return mergeFrom((mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply other) {
        if (other == mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt5_term_api.StopListeningReply)
    }

    // @@protoc_insertion_point(class_scope:mt5_term_api.StopListeningReply)
    private static final mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply();
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StopListeningReply>
        PARSER = new com.google.protobuf.AbstractParser<StopListeningReply>() {
      @java.lang.Override
      public StopListeningReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new StopListeningReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<StopListeningReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StopListeningReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt5_term_api.Mt5TermApiHealthCheck.StopListeningReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthCheckRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt5_term_api.HealthCheckRequest)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code mt5_term_api.HealthCheckRequest}
   */
  public static final class HealthCheckRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt5_term_api.HealthCheckRequest)
      HealthCheckRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckRequest.newBuilder() to construct.
    private HealthCheckRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckRequest() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HealthCheckRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HealthCheckRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest.class, mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest)) {
        return super.equals(obj);
      }
      mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest other = (mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest) obj;

      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt5_term_api.HealthCheckRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt5_term_api.HealthCheckRequest)
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest.class, mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest.Builder.class);
      }

      // Construct using mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckRequest_descriptor;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest getDefaultInstanceForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest.getDefaultInstance();
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest build() {
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest buildPartial() {
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest result = new mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest) {
          return mergeFrom((mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest other) {
        if (other == mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt5_term_api.HealthCheckRequest)
    }

    // @@protoc_insertion_point(class_scope:mt5_term_api.HealthCheckRequest)
    private static final mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest();
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckRequest>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckRequest>() {
      @java.lang.Override
      public HealthCheckRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HealthCheckRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthCheckRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface HealthCheckReplyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mt5_term_api.HealthCheckReply)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool is_connected_to_server = 1;</code>
     * @return The isConnectedToServer.
     */
    boolean getIsConnectedToServer();

    /**
     * <code>int64 server_time_seconds = 2;</code>
     * @return The serverTimeSeconds.
     */
    long getServerTimeSeconds();
  }
  /**
   * Protobuf type {@code mt5_term_api.HealthCheckReply}
   */
  public static final class HealthCheckReply extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mt5_term_api.HealthCheckReply)
      HealthCheckReplyOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use HealthCheckReply.newBuilder() to construct.
    private HealthCheckReply(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private HealthCheckReply() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new HealthCheckReply();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private HealthCheckReply(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              isConnectedToServer_ = input.readBool();
              break;
            }
            case 16: {

              serverTimeSeconds_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckReply_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckReply_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply.class, mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply.Builder.class);
    }

    public static final int IS_CONNECTED_TO_SERVER_FIELD_NUMBER = 1;
    private boolean isConnectedToServer_;
    /**
     * <code>bool is_connected_to_server = 1;</code>
     * @return The isConnectedToServer.
     */
    @java.lang.Override
    public boolean getIsConnectedToServer() {
      return isConnectedToServer_;
    }

    public static final int SERVER_TIME_SECONDS_FIELD_NUMBER = 2;
    private long serverTimeSeconds_;
    /**
     * <code>int64 server_time_seconds = 2;</code>
     * @return The serverTimeSeconds.
     */
    @java.lang.Override
    public long getServerTimeSeconds() {
      return serverTimeSeconds_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (isConnectedToServer_ != false) {
        output.writeBool(1, isConnectedToServer_);
      }
      if (serverTimeSeconds_ != 0L) {
        output.writeInt64(2, serverTimeSeconds_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (isConnectedToServer_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, isConnectedToServer_);
      }
      if (serverTimeSeconds_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, serverTimeSeconds_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply)) {
        return super.equals(obj);
      }
      mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply other = (mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply) obj;

      if (getIsConnectedToServer()
          != other.getIsConnectedToServer()) return false;
      if (getServerTimeSeconds()
          != other.getServerTimeSeconds()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IS_CONNECTED_TO_SERVER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsConnectedToServer());
      hash = (37 * hash) + SERVER_TIME_SECONDS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getServerTimeSeconds());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mt5_term_api.HealthCheckReply}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mt5_term_api.HealthCheckReply)
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReplyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckReply_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckReply_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply.class, mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply.Builder.class);
      }

      // Construct using mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        isConnectedToServer_ = false;

        serverTimeSeconds_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.internal_static_mt5_term_api_HealthCheckReply_descriptor;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply getDefaultInstanceForType() {
        return mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply.getDefaultInstance();
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply build() {
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply buildPartial() {
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply result = new mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply(this);
        result.isConnectedToServer_ = isConnectedToServer_;
        result.serverTimeSeconds_ = serverTimeSeconds_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply) {
          return mergeFrom((mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply other) {
        if (other == mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply.getDefaultInstance()) return this;
        if (other.getIsConnectedToServer() != false) {
          setIsConnectedToServer(other.getIsConnectedToServer());
        }
        if (other.getServerTimeSeconds() != 0L) {
          setServerTimeSeconds(other.getServerTimeSeconds());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean isConnectedToServer_ ;
      /**
       * <code>bool is_connected_to_server = 1;</code>
       * @return The isConnectedToServer.
       */
      @java.lang.Override
      public boolean getIsConnectedToServer() {
        return isConnectedToServer_;
      }
      /**
       * <code>bool is_connected_to_server = 1;</code>
       * @param value The isConnectedToServer to set.
       * @return This builder for chaining.
       */
      public Builder setIsConnectedToServer(boolean value) {
        
        isConnectedToServer_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool is_connected_to_server = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIsConnectedToServer() {
        
        isConnectedToServer_ = false;
        onChanged();
        return this;
      }

      private long serverTimeSeconds_ ;
      /**
       * <code>int64 server_time_seconds = 2;</code>
       * @return The serverTimeSeconds.
       */
      @java.lang.Override
      public long getServerTimeSeconds() {
        return serverTimeSeconds_;
      }
      /**
       * <code>int64 server_time_seconds = 2;</code>
       * @param value The serverTimeSeconds to set.
       * @return This builder for chaining.
       */
      public Builder setServerTimeSeconds(long value) {
        
        serverTimeSeconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 server_time_seconds = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearServerTimeSeconds() {
        
        serverTimeSeconds_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mt5_term_api.HealthCheckReply)
    }

    // @@protoc_insertion_point(class_scope:mt5_term_api.HealthCheckReply)
    private static final mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply();
    }

    public static mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<HealthCheckReply>
        PARSER = new com.google.protobuf.AbstractParser<HealthCheckReply>() {
      @java.lang.Override
      public HealthCheckReply parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new HealthCheckReply(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<HealthCheckReply> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<HealthCheckReply> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public mt5_term_api.Mt5TermApiHealthCheck.HealthCheckReply getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt5_term_api_StopListeningRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt5_term_api_StopListeningRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt5_term_api_StopListeningReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt5_term_api_StopListeningReply_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt5_term_api_HealthCheckRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt5_term_api_HealthCheckRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mt5_term_api_HealthCheckReply_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mt5_term_api_HealthCheckReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037mt5-term-api-health-check.proto\022\014mt5_t" +
      "erm_api\"\026\n\024StopListeningRequest\"\024\n\022StopL" +
      "isteningReply\"\024\n\022HealthCheckRequest\"O\n\020H" +
      "ealthCheckReply\022\036\n\026is_connected_to_serve" +
      "r\030\001 \001(\010\022\033\n\023server_time_seconds\030\002 \001(\0032\252\001\n" +
      "\006Health\022I\n\005Check\022 .mt5_term_api.HealthCh" +
      "eckRequest\032\036.mt5_term_api.HealthCheckRep" +
      "ly\022U\n\rStopListening\022\".mt5_term_api.StopL" +
      "isteningRequest\032 .mt5_term_api.StopListe" +
      "ningReplyBBZ1git.mtapi.io/root/mrpc-prot" +
      "o.git/mt5/libraries/go\252\002\014mt5_term_apib\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_mt5_term_api_StopListeningRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mt5_term_api_StopListeningRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt5_term_api_StopListeningRequest_descriptor,
        new java.lang.String[] { });
    internal_static_mt5_term_api_StopListeningReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mt5_term_api_StopListeningReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt5_term_api_StopListeningReply_descriptor,
        new java.lang.String[] { });
    internal_static_mt5_term_api_HealthCheckRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mt5_term_api_HealthCheckRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt5_term_api_HealthCheckRequest_descriptor,
        new java.lang.String[] { });
    internal_static_mt5_term_api_HealthCheckReply_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_mt5_term_api_HealthCheckReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mt5_term_api_HealthCheckReply_descriptor,
        new java.lang.String[] { "IsConnectedToServer", "ServerTimeSeconds", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
