// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mt5-term-api-demo-account.proto

package mt5_term_api;

public final class Mt5TermApiDemoAccount {
  private Mt5TermApiDemoAccount() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037mt5-term-api-demo-account.proto\022\014mt5_t" +
      "erm_api\032\034google/api/annotations.proto\032\026m" +
      "t5-term-api-gui.proto2\213\002\n\013DemoAccount\022|\n" +
      "\017OpenDemoAccount\022\'.mt5_term_api.GuiDemoO" +
      "penAccountRequest\032%.mt5_term_api.GuiDemo" +
      "OpenAccountReply\"\031\202\323\344\223\002\023\022\021/DemoAccount/O" +
      "pen\022~\n\032DemoOpenAccountInteractive\022-.mt5_" +
      "term_api.GuiDemoInteractiveClientMessage" +
      "\032-.mt5_term_api.GuiDemoInteractiveServer" +
      "Message(\0010\001BBZ1git.mtapi.io/root/mrpc-pr" +
      "oto.git/mt5/libraries/go\252\002\014mt5_term_apib" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.api.AnnotationsProto.getDescriptor(),
          mt5_term_api.Mt5TermApiGui.getDescriptor(),
        });
    com.google.protobuf.ExtensionRegistry registry =
        com.google.protobuf.ExtensionRegistry.newInstance();
    registry.add(com.google.api.AnnotationsProto.http);
    com.google.protobuf.Descriptors.FileDescriptor
        .internalUpdateFileDescriptor(descriptor, registry);
    com.google.api.AnnotationsProto.getDescriptor();
    mt5_term_api.Mt5TermApiGui.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
